name: bumpyproject
channels:
  - conda-forge
dependencies:
  - python=3.11
  - azure-identity
  - python-dotenv
  - semver
  - tomlkit
  - pip
  - pip:
      - azure-mgmt-containerregistry
      - docker
      - azure-containerregistry
      - GitPython