name: bumpy-test

# Bump 0
on: push


jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          cache-env: true
          channels: conda-forge
          channel-priority: strict
          environment-file: environment.yml

      - name: Test
        run: |
          pytest .
        working-directory: tests